### ISSUE TITLE
How to resume sampling to make the chain longer?

### ISSUE THREAD

**Issue by ajshajib** [cosmo-ethz/CosmoHammer#6]
My machine runs into a memory limit exceeded error when trying to run the sampler for a long number of iteration with lots of walkers. I looked at the code for the source of the error and it looks like Emcee needs to create the entire array with dimension (nwalker, niteration, ndim) at initiation and then concatenates that array to some other array which requires twice the amount of memory needed to store the entire chain. I am thinking to circumvent this issue by running the chain for smaller number of iterations, then storing the chain into hard disk, then resuming sampling from last iteration state, and doing this repetitively until the desired chain length is achieved. Is it possible to resume sampling from the last iteration state and automatically save the newly sampled states at the end of the already saved output files? If so, how can this be done?

**Comment by jakeret** [comment]
Hi, sorry for the late reply. 

It's been a while but if I remember correctly there is an option to [reuse the burn in phase](https://github.com/cosmo-ethz/CosmoHammer/blob/master/cosmoHammer/CosmoHammerSampler.py#L34). 

You have to write a script that renames the file from the sampling phase and CosmoHammer picks it up as new starting point
